version: '3.4'

services:
  shopping.api:
    image: ${DOCKER_REGISTRY-}shoppingapi
    build:
      context: .
      dockerfile: Shopping.API/Dockerfile

  shoppingclient:
    image: ${DOCKER_REGISTRY-}shoppingclient
    build:
      context: .
      dockerfile: ShoppingClient/Dockerfile

  shopping.db:
    image: mongo

